spring:
  cloud:
    function.definition: uppercase|lowercase|uppercase
    stream.bindings.uppercaselowercaseuppercase-in-0.destination: input-topic-name
    stream.bindings.uppercaselowercaseuppercase-out-0.destination: output-topic-name
